# -*- coding: utf-8 -*-
"""CNN Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAP2YT4Xi6W9FoEgf51PmFhWsy43soY_
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import layers, Sequential
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.metrics import classification_report, confusion_matrix

def load_and_preprocess_data(train_size=None):
    """Loads, normalizes, and one-hot encodes the MNIST dataset."""
    (X_train, y_train), (X_test, y_test) = mnist.load_data()

    # Normalize pixel values to [0, 1] and reshape for CNN
    X_train = (X_train.astype('float32') / 255.0).reshape(-1, 28, 28, 1)
    X_test = (X_test.astype('float32') / 255.0).reshape(-1, 28, 28, 1)

    # One-hot encode labels
    y_train_encoded = to_categorical(y_train, 10)
    y_test_encoded = to_categorical(y_test, 10)

    # Optional subset for faster training
    if train_size:
        X_train = X_train[:train_size]
        y_train_encoded = y_train_encoded[:train_size]
        y_train = y_train[:train_size]

    return (X_train, y_train_encoded, y_train), (X_test, y_test_encoded, y_test)

def build_cnn_model(input_shape=(28, 28, 1), num_classes=10):
    """Builds and compiles the CNN architecture."""
    model = Sequential([
        # First Convolutional Block
        layers.Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.25),

        # Second Convolutional Block
        layers.Conv2D(64, (3, 3), activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.25),

        # Third Convolutional Block
        layers.Conv2D(128, (3, 3), activation='relu'),
        layers.BatchNormalization(),
        layers.Dropout(0.25),

        # Flatten and Dense Classification Head
        layers.Flatten(),
        layers.Dense(128, activation='relu'),
        layers.BatchNormalization(),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation='softmax')
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

def train_model(model, X_train, y_train, epochs=50, batch_size=64):
    """Trains the model with dynamic learning rate and early stopping callbacks."""
    callbacks = [
        EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=1e-6, verbose=1)
    ]

    history = model.fit(
        X_train, y_train,
        batch_size=batch_size,
        epochs=epochs,
        validation_split=0.2,
        callbacks=callbacks,
        verbose=1
    )
    return history

def evaluate_and_plot(model, history, X_test, y_test_encoded, y_test_true):
    """Evaluates test data and visualizes training history alongside a confusion matrix."""
    # Plot training and validation metrics
    sns.set_style('whitegrid')
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    axes[0].plot(history.history['accuracy'], label='Train', linewidth=2)
    axes[0].plot(history.history['val_accuracy'], label='Validation', linewidth=2)
    axes[0].set_title('Model Accuracy', fontweight='bold')
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('Accuracy')
    axes[0].legend()

    axes[1].plot(history.history['loss'], label='Train', linewidth=2)
    axes[1].plot(history.history['val_loss'], label='Validation', linewidth=2)
    axes[1].set_title('Model Loss', fontweight='bold')
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('Loss')
    axes[1].legend()
    plt.tight_layout()
    plt.show()

    # Evaluate numerical metrics
    test_loss, test_acc = model.evaluate(X_test, y_test_encoded, verbose=0)
    print(f"\nTest Accuracy: {test_acc:.4f} | Test Loss: {test_loss:.4f}")

    # Generate predictions
    y_pred = np.argmax(model.predict(X_test, verbose=0), axis=1)
    print("\nClassification Report:")
    print(classification_report(y_test_true, y_pred))

    # Plot confusion matrix
    plt.figure(figsize=(10, 8))
    sns.heatmap(confusion_matrix(y_test_true, y_pred), annot=True, fmt='d', cmap='Blues')
    plt.title('Confusion Matrix', fontweight='bold')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.tight_layout()
    plt.show()

def main():
    # Set random seeds for reproducibility
    np.random.seed(42)
    tf.random.set_seed(42)

    print("Loading and preprocessing data...")
    train_data, test_data = load_and_preprocess_data(train_size=10000)
    X_train, y_train_enc, _ = train_data
    X_test, y_test_enc, y_test_true = test_data

    print("\nBuilding model architecture...")
    model = build_cnn_model()

    print("\nStarting model training...")
    history = train_model(model, X_train, y_train_enc)

    print("\nEvaluating model performance...")
    evaluate_and_plot(model, history, X_test, y_test_enc, y_test_true)

    # Save the trained model to folder
    model.save('mnist_model.keras')
    print("\nModel successfully saved as 'mnist_model.keras'")

if __name__ == "__main__":
    main()

import numpy as np
import tensorflow as tf
from PIL import Image

def load_and_prep_image(image_path):
    """
    Loads an image and preprocesses it for the MNIST CNN.
    MNIST images are 28x28 pixels, grayscale, with values between 0 and 1.
    """
    # 1. Load the image and convert it to grayscale ('L')
    img = Image.open(image_path).convert('L')

    # 2. Resize it to 28x28 pixels (the exact size MNIST models expect)
    img = img.resize((28, 28))

    # 3. Convert the image to a numpy array
    img_array = np.array(img)

    # Note: MNIST is typically white text on a black background.
    # If your image is black text on a white background, uncomment the next line to invert it:
    # img_array = 255 - img_array

    # 4. Normalize the pixel values to be between 0 and 1
    img_array = img_array.astype('float32') / 255.0

    # 5. Reshape to match the CNN's expected input format: (batch_size, height, width, channels)
    # Even for a single image, Keras expects a batch dimension, so the shape becomes (1, 28, 28, 1)
    img_array = np.expand_dims(img_array, axis=-1) # Add channel dimension
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension

    return img_array

def predict_digit(model_path, image_path):
    """
    Loads the saved model and predicts the digit in the given image.
    """
    try:
        # Load the saved model (assumes you saved it via model.save('my_model.keras'))
        print("Loading model...")
        model = tf.keras.models.load_model(model_path)

        # Preprocess the target image
        print("Processing image...")
        processed_image = load_and_prep_image(image_path)

        # Predict the digit
        # model.predict returns an array of probabilities for each class (0-9)
        predictions = model.predict(processed_image, verbose=0)

        # Find the index with the highest probability
        predicted_class = np.argmax(predictions[0])
        confidence = np.max(predictions[0]) * 100

        print("\n--- Prediction Results ---")
        print(f"Predicted Digit: {predicted_class}")
        print(f"Confidence:      {confidence:.2f}%")

        return predicted_class

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    MODEL_FILE = 'mnist_model.keras'
    IMAGE_FILE = 'MNIST-1.png'

    predict_digit(MODEL_FILE, IMAGE_FILE)